export const projects = [
  {
    id: "mission-01",
    title: "Quantum Ledger",
    subtitle: "NEXT-GEN FINTECH ECOSYSTEM",
    description: "A secure, decentralized financial dashboard featuring real-time market tracking, automated portfolio rebalancing, and biometric security layers.",
    problem: "Traditional financial platforms lack transparency and real-time responsiveness, often leaving users with stale data and vulnerable to centralized failures.",
    solution: "Developed a decentralized architecture using Supabase and real-time streams, ensuring sub-second data propagation and cryptographic ownership of financial records.",
    impact: "Reduced data latency by 85% and increased user engagement by providing actionable, real-time insights with military-grade security.",
    tags: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Chart.js"],
    status: "COMPLETED",
    category: "Fullstack",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=2832&ixlib=rb-4.0.3",
    color: "var(--color-arc-blue)",
    link: "#",
    github: "#"
  },
  {
    id: "mission-02",
    title: "Aether OS",
    subtitle: "HOLOGRAPHIC CLOUD DESKTOP",
    description: "A web-based operating system designed for spatial computing. Features a custom window manager, virtual file system, and multi-threaded processing.",
    problem: "Spatial computing environments require high-performance window management that traditional web frameworks aren't optimized for.",
    solution: "Built a custom kernel using Web Workers for multi-threaded processing and Three.js for a performant 3D windowing environment.",
    impact: "Created the first stable 3D web desktop capable of running complex multi-threaded applications without blocking the main UI thread.",
    tags: ["React", "Three.js", "Web Workers", "Node.js", "Redis"],
    status: "ACTIVE",
    category: "Frontend",
    image: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&q=80&w=2854&ixlib=rb-4.0.3",
    color: "var(--color-marvel-red)",
    link: "#",
    github: "#"
  },
  {
    id: "mission-03",
    title: "Project Jarvis",
    subtitle: "AI NEURAL INTERFACE",
    description: "An advanced LLM integration system that processes multi-modal inputs to automate complex developer workflows and architectural decisions.",
    problem: "Developers spend 40% of their time on boilerplate and documentation instead of core architectural logic.",
    solution: "Integrated Gemini 1.5 Pro with a custom context-aware RAG system that automates the generation of architecture diagrams and boilerplate code.",
    impact: "Increased developer productivity by 60% and reduced architectural errors by providing real-time AI validation against project requirements.",
    tags: ["Python", "TensorFlow", "FastAPI", "OpenAI", "Docker"],
    status: "COMPLETED",
    category: "AI",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=2832&ixlib=rb-4.0.3",
    color: "var(--color-stark-gold)",
    link: "#",
    github: "#"
  },
  {
    id: "mission-04",
    title: "Sentinel Mesh",
    subtitle: "CYBERSECURITY PROTOCOL",
    description: "A real-time network monitoring tool that uses machine learning to detect and mitigate zero-day vulnerabilities across distributed systems.",
    problem: "Modern microservices are vulnerable to rapid, distributed attacks that outpace human security response times.",
    solution: "Deployed a gRPC-based mesh that uses machine learning models to identify anomaly patterns and automatically isolate compromised nodes.",
    impact: "Successfully prevented 12 large-scale simulated attacks with 99.9% detection accuracy and sub-50ms isolation time.",
    tags: ["Go", "Kubernetes", "gRPC", "Prometheus", "Elk Stack"],
    status: "COMPLETED",
    category: "Backend",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=2940&ixlib=rb-4.0.3",
    color: "var(--color-arc-blue)",
    link: "#",
    github: "#"
  },
  {
    id: "mission-05",
    title: "Nebula Core",
    subtitle: "DISTRIBUTED CLOUD ENGINE",
    description: "A high-performance cloud orchestration engine designed to manage thousands of microservices with sub-millisecond latency and auto-scaling.",
    problem: "Existing cloud orchestrators suffer from significant overhead when scaling to tens of thousands of microservices.",
    solution: "Architected a decentralized control plane using Rust and Wasm for ultra-low latency execution and minimal resource footprint.",
    impact: "Reduced orchestration overhead by 70% while improving fault tolerance through a leaderless consensus protocol.",
    tags: ["Rust", "Wasm", "NATS", "PostgreSQL", "Terraform"],
    status: "CLASSIFIED",
    category: "Backend",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=2944&ixlib=rb-4.0.3",
    color: "var(--color-marvel-red)",
    link: "#",
    github: "#"
  },
  {
    id: "mission-06",
    title: "Titan UI",
    subtitle: "3D COMPONENT LIBRARY",
    description: "A comprehensive design system and component library built specifically for high-end cinematic web applications and 3D interfaces.",
    problem: "Generic component libraries fail to deliver the high-fidelity, cinematic experience required for premium web applications.",
    solution: "Created a GLSL-optimized component system that leverages GSAP and Framer Motion for complex, high-performance visual transitions.",
    impact: "Provided a standardized toolkit for developers to build AAA-quality web interfaces with minimal performance trade-offs.",
    tags: ["React", "GLSL", "GSAP", "Storybook", "Framer"],
    status: "COMPLETED",
    category: "Frontend",
    image: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&q=80&w=2787&ixlib=rb-4.0.3",
    color: "var(--color-stark-gold)",
    link: "#",
    github: "#"
  }
];
