export const testimonialsData = [
  {
    id: "TS-001",
    name: "Tony Stark",
    role: "CEO & Founder",
    company: "Stark Industries",
    content: "The neural interface Keerthi developed for the Mark LXXXV is impeccable. Clean code, modular architecture, and zero latency. A true visionary in the field of technical engineering.",
    avatar: "/avatars/tony-stark.jpg",
    transmissionTime: "08:14:22",
    clearance: "LEVEL 10",
  },
  {
    id: "TS-002",
    name: "Nick Fury",
    role: "Director",
    company: "S.H.I.E.L.D.",
    content: "We needed a secure, encrypted dashboard for tracking global anomalies. Keerthi delivered a system that even Hydra couldn't penetrate. Efficiency is high, and the UI is intuitive enough for an agent with one eye.",
    avatar: "/avatars/nick-fury.jpg",
    transmissionTime: "12:05:48",
    clearance: "OVERRIDE",
  },
  {
    id: "TS-003",
    name: "Pepper Potts",
    role: "CEO",
    company: "Resilient Tech",
    content: "Managing the logistics of a multi-billion dollar tech conglomerate requires precision. The data visualization tools built by Keerthi have streamlined our global operations by 40%. Highly recommended.",
    avatar: "/avatars/pepper-potts.jpg",
    transmissionTime: "15:30:10",
    clearance: "ADMIN",
  },
  {
    id: "TS-004",
    name: "Bruce Banner",
    role: "Head of Bio-Tech",
    company: "Avengers Labs",
    content: "The gamma radiation monitoring system Keerthi designed is robust. The error handling is particularly impressive—it stays calm even when the data gets... angry. A brilliant mind.",
    avatar: "/avatars/bruce-banner.jpg",
    transmissionTime: "09:42:15",
    clearance: "SCIENTIFIC",
  },
  {
    id: "TS-005",
    name: "Shuri",
    role: "Princess & Lead Scientist",
    company: "Wakanda Design Group",
    content: "I've seen many systems, but the elegance of this codebase rivals our Vibranium tech. The integration of AI and real-time data streaming is state-of-the-art. Wakanda salutes this talent.",
    avatar: "/avatars/shuri.jpg",
    transmissionTime: "22:11:05",
    clearance: "ROYAL",
  }
];
